var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,h="function"==typeof importScripts,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",ea,r,fa;
if(m){var fs=require("fs"),ha=require("path");q=h?ha.dirname(q)+"/":__dirname+"/";ea=(a,b)=>{a=ia(a)?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};fa=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=ia(a)?new URL(a):ha.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof ja||a.context instanceof ja))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||h)h?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,
!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=g.print||console.log.bind(console),v=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.thisProgram&&(ba=g.thisProgram);g.quit&&(ca=g.quit);var w;g.wasmBinary&&(w=g.wasmBinary);"object"!=typeof WebAssembly&&la("no native wasm support detected");
var ma,na=!1,x,y,oa,A,B;function pa(){var a=ma.buffer;g.HEAP8=x=new Int8Array(a);g.HEAP16=oa=new Int16Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU32=B=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var qa=[],ra=[],sa=[];function ta(){var a=g.preRun.shift();qa.unshift(a)}var C=0,ua=null,D=null;
function la(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";v(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va=a=>a.startsWith("data:application/octet-stream;base64,"),ia=a=>a.startsWith("file://"),E;E="index.wasm";if(!va(E)){var wa=E;E=g.locateFile?g.locateFile(wa,q):q+wa}function xa(a){if(a==E&&w)return new Uint8Array(w);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}
function ya(a){if(!w&&(da||h)){if("function"==typeof fetch&&!ia(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>xa(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>xa(a))}function za(a,b,c){return ya(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);la(d)})}
function Aa(a,b){var c=E;w||"function"!=typeof WebAssembly.instantiateStreaming||va(c)||ia(c)||m||"function"!=typeof fetch?za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return za(c,a,b)}))}var G,Ba;function ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ca=a=>{for(;0<a.length;)a.shift()(g)},Da=g.noExitRuntime||!0,Ea=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},H=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ea(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Fa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&(b=b.substr(0,b.length-1));return a+b},Ga=a=>{if("/"===a)return"/";a=H(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ha=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(m)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}la("initRandomDevice")},Ia=a=>(Ia=Ha())(a);
function Ja(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ea(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,I=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
La=[],Na=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Oa=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&
63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],u:b};Ra(a,Sa)}
var Sa={open(a){var b=Pa[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close(a){a.tty.u.fsync(a.tty)},fsync(a){a.tty.u.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.u.M)throw new K(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.u.M(a.tty)}catch(n){throw new K(29);}if(void 0===k&&0===e)throw new K(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.u.G)throw new K(60);try{for(var e=0;e<d;e++)a.tty.u.G(a.tty,b[c+e])}catch(f){throw new K(29);
}d&&(a.node.timestamp=Date.now());return e}},Ta={M(){a:{if(!La.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Na(a)+1);a=Oa(a,b,0,b.length);b.length=
a;La=b}a=La.shift()}return a},G(a,b){null===b||10===b?(ka(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ka(I(a.output,0)),a.output=[])},T(){return{da:25856,fa:5,ba:191,ea:35387,aa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},U(){return 0},V(){return[24,80]}},Ua={G(a,b){null===b||10===b?(v(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(v(I(a.output,0)),a.output=[])}};
function Va(a,b){var c=a.g?a.g.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.g,a.g=new Uint8Array(b),0<a.j&&a.g.set(c.subarray(0,a.j),0))}
var L={l:null,s(){return L.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.l||(L.l={dir:{node:{v:L.h.v,m:L.h.m,lookup:L.h.lookup,C:L.h.C,rename:L.h.rename,unlink:L.h.unlink,rmdir:L.h.rmdir,readdir:L.h.readdir,symlink:L.h.symlink},stream:{A:L.i.A}},file:{node:{v:L.h.v,m:L.h.m},stream:{A:L.i.A,read:L.i.read,write:L.i.write,I:L.i.I,N:L.i.N,P:L.i.P}},link:{node:{v:L.h.v,m:L.h.m,readlink:L.h.readlink},stream:{}},J:{node:{v:L.h.v,m:L.h.m},stream:Wa}});
c=Xa(a,b,c,d);16384===(c.mode&61440)?(c.h=L.l.dir.node,c.i=L.l.dir.stream,c.g={}):32768===(c.mode&61440)?(c.h=L.l.file.node,c.i=L.l.file.stream,c.j=0,c.g=null):40960===(c.mode&61440)?(c.h=L.l.link.node,c.i=L.l.link.stream):8192===(c.mode&61440)&&(c.h=L.l.J.node,c.i=L.l.J.stream);c.timestamp=Date.now();a&&(a.g[b]=c,a.timestamp=c.timestamp);return c},ga(a){return a.g?a.g.subarray?a.g.subarray(0,a.j):new Uint8Array(a.g):new Uint8Array(0)},h:{v(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;
b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.j:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.R=4096;b.blocks=Math.ceil(b.size/b.R);return b},m(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.j!=b))if(0==b)a.g=null,a.j=0;else{var c=a.g;a.g=new Uint8Array(b);
c&&a.g.set(c.subarray(0,Math.min(b,a.j)));a.j=b}},lookup(){throw Ya[44];},C(a,b,c,d){return L.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=Za(b,c)}catch(f){}if(d)for(var e in d.g)throw new K(55);}delete a.parent.g[a.name];a.parent.timestamp=Date.now();a.name=c;b.g[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.g[b];a.timestamp=Date.now()},rmdir(a,b){var c=Za(a,b),d;for(d in c.g)throw new K(55);delete a.g[b];a.timestamp=Date.now()},readdir(a){var b=
[".",".."],c;for(c in a.g)a.g.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},i:{read(a,b,c,d,e){var f=a.node.g;if(e>=a.node.j)return 0;a=Math.min(a.node.j-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===x.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.g||a.g.subarray)){if(f)return a.g=
b.subarray(c,c+d),a.j=d;if(0===a.j&&0===e)return a.g=b.slice(c,c+d),a.j=d;if(e+d<=a.j)return a.g.set(b.subarray(c,c+d),e),d}Va(a,e+d);if(a.g.subarray&&b.subarray)a.g.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.g[e+f]=b[c+f];a.j=Math.max(a.j,e+d);return d},A(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.j);if(0>b)throw new K(28);return b},I(a,b,c){Va(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},N(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.g;if(e&
2||a.buffer!==x.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;la();b=void 0;if(!b)throw new K(48);x.set(a,b)}else c=!1,b=a.byteOffset;return{ia:b,$:c}},P(a,b,c,d){L.i.write(a,b,0,d,c,!1);return 0}}},$a=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ab=null,bb={},M=[],cb=1,N=null,db=!0,K=null,Ya={};
function O(a,b={}){a=Ja(a);if(!a)return{path:"",node:null};b=Object.assign({L:!0,H:0},b);if(8<b.H)throw new K(32);a=a.split("/").filter(k=>!!k);for(var c=ab,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Za(c,a[e]);d=H(d+"/"+a[e]);c.D&&(!f||f&&b.L)&&(c=c.D.root);if(!f||b.K)for(f=0;40960===(c.mode&61440);)if(c=eb(d),d=Ja(Fa(d),c),c=O(d,{H:b.H+1}).node,40<f++)throw new K(32);}return{path:d,node:c}}
function fb(a){for(var b;;){if(a===a.parent)return a=a.s.O,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function Za(a,b){var c;if(c=(c=hb(a,"x"))?c:a.h.lookup?0:2)throw new K(c,a);for(c=N[gb(a.id,b)];c;c=c.X){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.lookup(a,b)}
function Xa(a,b,c,d){a=new ib(a,b,c,d);b=gb(a.parent.id,a.name);a.X=N[b];return N[b]=a}function jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function hb(a,b){if(db)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function kb(a,b){try{return Za(a,b),20}catch(c){}return hb(a,"wx")}function lb(){for(var a=0;4096>=a;a++)if(!M[a])return a;throw new K(33);}
function P(a){a=M[a];if(!a)throw new K(8);return a}function mb(a,b=-1){Q||(Q=function(){this.B={}},Q.prototype={},Object.defineProperties(Q.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.B.flags},set(c){this.B.flags=c}},position:{get(){return this.B.position},set(c){this.B.position=c}}}));a=Object.assign(new Q,a);-1==b&&(b=lb());a.fd=b;return M[b]=a}var Wa={open(a){a.i=bb[a.node.rdev].i;a.i.open&&a.i.open(a)},A(){throw new K(70);}};
function Ra(a,b){bb[a]={i:b}}function nb(a,b){var c="/"===b,d=!b;if(c&&ab)throw new K(10);if(!c&&!d){var e=O(b,{L:!1});b=e.path;e=e.node;if(e.D)throw new K(10);if(16384!==(e.mode&61440))throw new K(54);}b={type:a,ha:{},O:b,W:[]};a=a.s(b);a.s=b;b.root=a;c?ab=a:e&&(e.D=b,e.s&&e.s.W.push(b))}function ob(a,b,c){var d=O(a,{parent:!0}).node;a=Ga(a);if(!a||"."===a||".."===a)throw new K(28);var e=kb(d,a);if(e)throw new K(e);if(!d.h.C)throw new K(63);return d.h.C(d,a,b,c)}
function R(a){return ob(a,16895,0)}function pb(a,b,c){"undefined"==typeof c&&(c=b,b=438);ob(a,b|8192,c)}function qb(a,b){if(!Ja(a))throw new K(44);var c=O(b,{parent:!0}).node;if(!c)throw new K(44);b=Ga(b);var d=kb(c,b);if(d)throw new K(d);if(!c.h.symlink)throw new K(63);c.h.symlink(c,b,a)}function eb(a){a=O(a).node;if(!a)throw new K(44);if(!a.h.readlink)throw new K(28);return Ja(fb(a.parent),a.h.readlink(a))}
function rb(a,b,c){if(""===a)throw new K(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=H(a);try{e=O(a,{K:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new K(20);}else e=ob(a,c,0),d=!0;if(!e)throw new K(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new K(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==jb(b)||b&512)?31:hb(e,jb(b)):44))throw new K(c);if(b&512&&!d){c=e;c="string"==typeof c?O(c,{K:!0}).node:c;if(!c.h.m)throw new K(63);if(16384===(c.mode&61440))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(d=hb(c,"w"))throw new K(d);c.h.m(c,{size:0,timestamp:Date.now()})}b&=-131713;e=mb({node:e,path:fb(e),flags:b,seekable:!0,position:0,i:e.i,Z:[],error:!1});e.i.open&&e.i.open(e);!g.logReadFiles||b&1||(sb||(sb={}),a in
sb||(sb[a]=1));return e}function tb(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.i.A)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.i.A(a,b,c);a.Z=[]}function ub(){K||(K=function(a,b){this.name="ErrnoError";this.node=b;this.Y=function(c){this.o=c};this.Y(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(a=>{Ya[a]=new K(a);Ya[a].stack="<generic error, no stack>"}))}var vb;
function S(a,b,c){a=H("/dev/"+a);var d=$a(!!b,!!c);wb||(wb=64);var e=wb++<<8|0;Ra(e,{open(f){f.seekable=!1},close(){c&&c.buffer&&c.buffer.length&&c(10)},read(f,k,n,u){for(var l=0,p=0;p<u;p++){try{var t=b()}catch(z){throw new K(29);}if(void 0===t&&0===l)throw new K(6);if(null===t||void 0===t)break;l++;k[n+p]=t}l&&(f.node.timestamp=Date.now());return l},write(f,k,n,u){for(var l=0;l<u;l++)try{c(k[n+l])}catch(p){throw new K(29);}u&&(f.node.timestamp=Date.now());return l}});pb(a,d,e)}var wb,T={},Q,sb;
function xb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":P(a).path;if(0==b.length)throw new K(44);return H(a+"/"+b)}var U=void 0;function V(){var a=A[+U>>2];U+=4;return a}
var yb={},Ab=()=>{if(!zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in yb)void 0===yb[b]?delete a[b]:a[b]=yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);zb=c}return zb},zb,Bb=[],Cb,Gb=(a,b,c,d)=>{var e={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=Na(l)+1;var t=Db(p);Oa(l,y,t,p);p=t}return p},array:l=>{var p=
Db(l.length);x.set(l,p);return p}};a=g["_"+a];var f=[],k=0;if(d)for(var n=0;n<d.length;n++){var u=e[c[n]];u?(0===k&&(k=Eb()),f[n]=u(d[n])):f[n]=d[n]}c=a.apply(null,f);return c=function(l){0!==k&&Fb(k);return"string"===b?l?I(y,l):"":"boolean"===b?!!l:l}(c)};function ib(a,b,c,d){a||(a=this);this.parent=a;this.s=a.s;this.D=null;this.id=cb++;this.name=b;this.mode=c;this.h={};this.i={};this.rdev=d}
Object.defineProperties(ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});ub();N=Array(4096);nb(L,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");Ra(259,{read:()=>0,write:(d,e,f,k)=>k});pb("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);pb("/dev/tty",1280);pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ia(a).byteLength);return a[--b]};S("random",c);S("urandom",c);R("/dev/shm");R("/dev/shm/tmp")})();
(function(){R("/proc");var a=R("/proc/self");R("/proc/self/fd");nb({s(){var b=Xa(a,"fd",16895,73);b.h={lookup(c,d){var e=P(+d);c={parent:null,s:{O:"fake"},h:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Jb={__syscall_fcntl64:function(a,b,c){U=c;try{var d=P(a);switch(b){case 0:var e=V();if(0>e)return-28;for(;M[e];)e++;return mb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=V(),d.flags|=e,0;case 5:return e=V(),oa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return A[Hb()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof T||"ErrnoError"!==f.name)throw f;return-f.o}},__syscall_getcwd:function(a,b){try{if(0===b)return-28;var c=Na("/")+1;if(b<
c)return-68;Oa("/",y,a,b);return c}catch(d){if("undefined"==typeof T||"ErrnoError"!==d.name)throw d;return-d.o}},__syscall_ioctl:function(a,b,c){U=c;try{var d=P(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.u.T){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=V();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=0;32>f;f++)x[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;
if(d.tty.u.U)for(e=V(),b=[],f=0;32>f;f++)b.push(x[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=V();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=V();if(!d.i.S)throw new K(59);return d.i.S(d,b,e);case 21523:if(!d.tty)return-59;d.tty.u.V&&(f=[24,80],e=V(),oa[e>>1]=f[0],oa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(k){if("undefined"==typeof T||"ErrnoError"!==k.name)throw k;return-k.o}},__syscall_openat:function(a,
b,c,d){U=d;try{b=b?I(y,b):"";b=xb(a,b);var e=d?V():0;return rb(b,c,e).fd}catch(f){if("undefined"==typeof T||"ErrnoError"!==f.name)throw f;return-f.o}},__syscall_readlinkat:function(a,b,c,d){try{b=b?I(y,b):"";b=xb(a,b);if(0>=d)return-28;var e=eb(b),f=Math.min(d,Na(e)),k=x[c+f];Oa(e,y,c,d+1);x[c+f]=k;return f}catch(n){if("undefined"==typeof T||"ErrnoError"!==n.name)throw n;return-n.o}},_emscripten_get_now_is_monotonic:()=>!0,_emscripten_throw_longjmp:()=>{throw Infinity;},emscripten_date_now:()=>Date.now(),
emscripten_get_now:()=>performance.now(),emscripten_memcpy_js:(a,b,c)=>y.copyWithin(a,b,b+c),emscripten_resize_heap:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ma.buffer.byteLength+65535)/65536;try{ma.grow(e);pa();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},environ_get:(a,b)=>{var c=0;Ab().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=
f;for(f=0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:(a,b)=>{var c=Ab();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},exit:a=>{if(!Da){if(g.onExit)g.onExit(a);na=!0}ca(a,new ja(a))},fd_close:function(a){try{var b=P(a);if(null===b.fd)throw new K(8);b.F&&(b.F=null);try{b.i.close&&b.i.close(b)}catch(c){throw c;}finally{M[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof T||"ErrnoError"!==c.name)throw c;return c.o}},
fd_read:function(a,b,c,d){try{a:{var e=P(a);a=b;for(var f,k=b=0;k<c;k++){var n=B[a>>2],u=B[a+4>>2];a+=8;var l=e,p=n,t=u,z=f,Ma=x;if(0>t||0>z)throw new K(28);if(null===l.fd)throw new K(8);if(1===(l.flags&2097155))throw new K(8);if(16384===(l.node.mode&61440))throw new K(31);if(!l.i.read)throw new K(28);var W="undefined"!=typeof z;if(!W)z=l.position;else if(!l.seekable)throw new K(70);var X=l.i.read(l,Ma,p,t,z);W||(l.position+=X);var F=X;if(0>F){var Y=-1;break a}b+=F;if(F<u)break;"undefined"!==typeof f&&
(f+=F)}Y=b}B[d>>2]=Y;return 0}catch(J){if("undefined"==typeof T||"ErrnoError"!==J.name)throw J;return J.o}},fd_seek:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=P(a);tb(f,b,d);Ba=[f.position>>>0,(G=f.position,1<=+Math.abs(G)?0<G?+Math.floor(G/4294967296)>>>0:~~+Math.ceil((G-+(~~G>>>0))/4294967296)>>>0:0)];A[e>>2]=Ba[0];A[e+4>>2]=Ba[1];f.F&&0===b&&0===d&&(f.F=null);return 0}catch(k){if("undefined"==typeof T||"ErrnoError"!==k.name)throw k;
return k.o}},fd_write:function(a,b,c,d){try{a:{var e=P(a);a=b;for(var f,k=b=0;k<c;k++){var n=B[a>>2],u=B[a+4>>2];a+=8;var l=e,p=n,t=u,z=f,Ma=x;if(0>t||0>z)throw new K(28);if(null===l.fd)throw new K(8);if(0===(l.flags&2097155))throw new K(8);if(16384===(l.node.mode&61440))throw new K(31);if(!l.i.write)throw new K(28);l.seekable&&l.flags&1024&&tb(l,0,2);var W="undefined"!=typeof z;if(!W)z=l.position;else if(!l.seekable)throw new K(70);var X=l.i.write(l,Ma,p,t,z,void 0);W||(l.position+=X);var F=X;if(0>
F){var Y=-1;break a}b+=F;"undefined"!==typeof f&&(f+=F)}Y=b}B[d>>2]=Y;return 0}catch(J){if("undefined"==typeof T||"ErrnoError"!==J.name)throw J;return J.o}},invoke_vii:Ib,system:a=>{if(m){if(!a)return 1;a=a?I(y,a):"";if(!a.length)return 0;a=require("child_process").ka(a,[],{ja:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2})(a.signal)):
a.status<<8|0}if(!a)return 0;A[Hb()>>2]=52;return-1}},Z=function(){function a(c){Z=c.exports;ma=Z.memory;pa();Cb=Z.__indirect_function_table;ra.unshift(Z.__wasm_call_ctors);C--;g.monitorRunDependencies&&g.monitorRunDependencies(C);0==C&&(null!==ua&&(clearInterval(ua),ua=null),D&&(c=D,D=null,c()));return Z}var b={env:Jb,wasi_snapshot_preview1:Jb};C++;g.monitorRunDependencies&&g.monitorRunDependencies(C);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return v(`Module.instantiateWasm callback failed with error: ${c}`),
!1}Aa(b,function(c){a(c.instance)});return{}}();g._new_state=()=>(g._new_state=Z.new_state)();g._free_state=()=>(g._free_state=Z.free_state)();g._run_tea=a=>(g._run_tea=Z.run_tea)(a);var Hb=()=>(Hb=Z.__errno_location)(),Kb=(a,b)=>(Kb=Z.setThrew)(a,b),Eb=()=>(Eb=Z.stackSave)(),Fb=a=>(Fb=Z.stackRestore)(a),Db=a=>(Db=Z.stackAlloc)(a);g.dynCall_jiji=(a,b,c,d,e)=>(g.dynCall_jiji=Z.dynCall_jiji)(a,b,c,d,e);
function Ib(a,b,c){var d=Eb();try{var e=Bb[a];e||(a>=Bb.length&&(Bb.length=a+1),Bb[a]=e=Cb.get(a));e(b,c)}catch(f){Fb(d);if(f!==f+0)throw f;Kb(1,0)}}g.ccall=Gb;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:function(){return Gb(a,b,c,arguments,d)}};var Lb;D=function Mb(){Lb||Nb();Lb||(D=Mb)};
function Nb(){function a(){if(!Lb&&(Lb=!0,g.calledRun=!0,!na)){g.noFSInit||vb||(vb=!0,ub(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?S("stdin",g.stdin):qb("/dev/tty","/dev/stdin"),g.stdout?S("stdout",null,g.stdout):qb("/dev/tty","/dev/stdout"),g.stderr?S("stderr",null,g.stderr):qb("/dev/tty1","/dev/stderr"),rb("/dev/stdin",0),rb("/dev/stdout",1),rb("/dev/stderr",1));db=!1;Ca(ra);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=
[g.postRun]);g.postRun.length;){var b=g.postRun.shift();sa.unshift(b)}Ca(sa)}}if(!(0<C)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ta();Ca(qa);0<C||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Nb();
