var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,h="function"==typeof importScripts,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",ea,r,v;
if(m){var fs=require("fs"),fa=require("path");q=h?fa.dirname(q)+"/":__dirname+"/";ea=(a,b)=>{a=a.startsWith("file://")?new URL(a):fa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=ea(a,!0);a.buffer||(a=new Uint8Array(a));return a};r=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):fa.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&
(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof ha||a.context instanceof ha))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(da||h)h?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},h&&
(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),r=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=g.print||console.log.bind(console),w=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.thisProgram&&(ba=g.thisProgram);g.quit&&(ca=g.quit);var x;
g.wasmBinary&&(x=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,y,la=!1,z,B,ma,C,D;function na(){var a=ka.buffer;g.HEAP8=z=new Int8Array(a);g.HEAP16=ma=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAPU32=D=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var oa,pa=[],qa=[],ra=[];
function sa(){var a=g.preRun.shift();pa.unshift(a)}var E=0,ta=null,G=null;function ja(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";w(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ua(a){return a.startsWith("data:application/octet-stream;base64,")}var H;H="index.wasm";if(!ua(H)){var va=H;H=g.locateFile?g.locateFile(va,q):q+va}
function wa(a){if(a==H&&x)return new Uint8Array(x);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}function xa(a){if(!x&&(da||h)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>wa(a));if(r)return new Promise((b,c)=>{r(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>wa(a))}
function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w("failed to asynchronously prepare wasm: "+d);ja(d)})}
function za(a,b){var c=H;x||"function"!=typeof WebAssembly.instantiateStreaming||ua(c)||c.startsWith("file://")||m||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w("wasm streaming compile failed: "+e);w("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}var I,Aa;function ha(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ba=a=>{for(;0<a.length;)a.shift()(g)},Ca=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},K=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ca(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Da=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,
b.length-1));return a+b},Ea=a=>{if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Fa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(m)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}ja("initRandomDevice")},Ga=a=>(Ga=Fa())(a);
function Ha(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ca(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
Ja=[],La=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ma=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&
63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},Na=[];function Oa(a,b){Na[a]={input:[],output:[],u:b};Pa(a,Qa)}
var Qa={open:function(a){var b=Na[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.u.fsync(a.tty)},fsync:function(a){a.tty.u.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.u.M)throw new M(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.u.M(a.tty)}catch(n){throw new M(29);}if(void 0===k&&0===e)throw new M(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.u.G)throw new M(60);try{for(var e=
0;e<d;e++)a.tty.u.G(a.tty,b[c+e])}catch(f){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},Ra={M:function(){a:{if(!Ja.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256,-1)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==
a&&(a+="\n"));if(!a){a=null;break a}b=Array(La(a)+1);a=Ma(a,b,0,b.length);b.length=a;Ja=b}a=Ja.shift()}return a},G:function(a,b){null===b||10===b?(ia(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ia(L(a.output,0)),a.output=[])},T:function(){return{da:25856,fa:5,ba:191,ea:35387,aa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},U:function(){return 0},V:function(){return[24,80]}},Sa={G:function(a,b){null===b||10===
b?(w(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(w(L(a.output,0)),a.output=[])}};function Ta(a,b){var c=a.g?a.g.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.g,a.g=new Uint8Array(b),0<a.j&&a.g.set(c.subarray(0,a.j),0))}
var N={l:null,s(){return N.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.l||(N.l={dir:{node:{v:N.h.v,m:N.h.m,lookup:N.h.lookup,C:N.h.C,rename:N.h.rename,unlink:N.h.unlink,rmdir:N.h.rmdir,readdir:N.h.readdir,symlink:N.h.symlink},stream:{A:N.i.A}},file:{node:{v:N.h.v,m:N.h.m},stream:{A:N.i.A,read:N.i.read,write:N.i.write,I:N.i.I,N:N.i.N,P:N.i.P}},link:{node:{v:N.h.v,m:N.h.m,readlink:N.h.readlink},stream:{}},J:{node:{v:N.h.v,m:N.h.m},stream:Ua}});
c=Va(a,b,c,d);16384===(c.mode&61440)?(c.h=N.l.dir.node,c.i=N.l.dir.stream,c.g={}):32768===(c.mode&61440)?(c.h=N.l.file.node,c.i=N.l.file.stream,c.j=0,c.g=null):40960===(c.mode&61440)?(c.h=N.l.link.node,c.i=N.l.link.stream):8192===(c.mode&61440)&&(c.h=N.l.J.node,c.i=N.l.J.stream);c.timestamp=Date.now();a&&(a.g[b]=c,a.timestamp=c.timestamp);return c},ga(a){return a.g?a.g.subarray?a.g.subarray(0,a.j):new Uint8Array(a.g):new Uint8Array(0)},h:{v(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;
b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.j:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.R=4096;b.blocks=Math.ceil(b.size/b.R);return b},m(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.j!=b))if(0==b)a.g=null,a.j=0;else{var c=a.g;a.g=new Uint8Array(b);
c&&a.g.set(c.subarray(0,Math.min(b,a.j)));a.j=b}},lookup(){throw Wa[44];},C(a,b,c,d){return N.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=Xa(b,c)}catch(f){}if(d)for(var e in d.g)throw new M(55);}delete a.parent.g[a.name];a.parent.timestamp=Date.now();a.name=c;b.g[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.g[b];a.timestamp=Date.now()},rmdir(a,b){var c=Xa(a,b),d;for(d in c.g)throw new M(55);delete a.g[b];a.timestamp=Date.now()},readdir(a){var b=
[".",".."],c;for(c in a.g)a.g.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},i:{read(a,b,c,d,e){var f=a.node.g;if(e>=a.node.j)return 0;a=Math.min(a.node.j-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===z.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.g||a.g.subarray)){if(f)return a.g=
b.subarray(c,c+d),a.j=d;if(0===a.j&&0===e)return a.g=b.slice(c,c+d),a.j=d;if(e+d<=a.j)return a.g.set(b.subarray(c,c+d),e),d}Ta(a,e+d);if(a.g.subarray&&b.subarray)a.g.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.g[e+f]=b[c+f];a.j=Math.max(a.j,e+d);return d},A(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.j);if(0>b)throw new M(28);return b},I(a,b,c){Ta(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},N(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.g;if(e&
2||a.buffer!==z.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;ja();b=void 0;if(!b)throw new M(48);z.set(a,b)}else c=!1,b=a.byteOffset;return{ia:b,$:c}},P(a,b,c,d){N.i.write(a,b,0,d,c,!1);return 0}}};function Ya(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var Za=null,$a={},ab=[],bb=1,O=null,cb=!0,M=null,Wa={},P=(a,b={})=>{a=Ha(a);if(!a)return{path:"",node:null};b=Object.assign({L:!0,H:0},b);if(8<b.H)throw new M(32);a=a.split("/").filter(k=>!!k);for(var c=Za,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Xa(c,a[e]);d=K(d+"/"+a[e]);c.D&&(!f||f&&b.L)&&(c=c.D.root);if(!f||b.K)for(f=0;40960===(c.mode&61440);)if(c=db(d),d=Ha(Da(d),c),c=P(d,{H:b.H+1}).node,40<f++)throw new M(32);}return{path:d,node:c}},eb=a=>{for(var b;;){if(a===a.parent)return a=
a.s.O,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},fb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length},Xa=(a,b)=>{var c;if(c=(c=gb(a,"x"))?c:a.h.lookup?0:2)throw new M(c,a);for(c=O[fb(a.id,b)];c;c=c.X){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.lookup(a,b)},Va=(a,b,c,d)=>{a=new hb(a,b,c,d);b=fb(a.parent.id,a.name);a.X=O[b];return O[b]=a},ib=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},gb=
(a,b)=>{if(cb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},jb=(a,b)=>{try{return Xa(a,b),20}catch(c){}return gb(a,"wx")},kb=()=>{for(var a=0;4096>=a;a++)if(!ab[a])return a;throw new M(33);},Q=a=>{a=ab[a];if(!a)throw new M(8);return a},lb=(a,b=-1)=>{R||(R=function(){this.B={}},R.prototype={},Object.defineProperties(R.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.B.flags},
set(c){this.B.flags=c}},position:{get(){return this.B.position},set(c){this.B.position=c}}}));a=Object.assign(new R,a);-1==b&&(b=kb());a.fd=b;return ab[b]=a},Ua={open:a=>{a.i=$a[a.node.rdev].i;a.i.open&&a.i.open(a)},A:()=>{throw new M(70);}},Pa=(a,b)=>{$a[a]={i:b}},mb=(a,b)=>{var c="/"===b,d=!b;if(c&&Za)throw new M(10);if(!c&&!d){var e=P(b,{L:!1});b=e.path;e=e.node;if(e.D)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,ha:{},O:b,W:[]};a=a.s(b);a.s=b;b.root=a;c?Za=a:e&&(e.D=b,
e.s&&e.s.W.push(b))},S=(a,b,c)=>{var d=P(a,{parent:!0}).node;a=Ea(a);if(!a||"."===a||".."===a)throw new M(28);var e=jb(d,a);if(e)throw new M(e);if(!d.h.C)throw new M(63);return d.h.C(d,a,b,c)},nb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);S(a,b|8192,c)},ob=(a,b)=>{if(!Ha(a))throw new M(44);var c=P(b,{parent:!0}).node;if(!c)throw new M(44);b=Ea(b);var d=jb(c,b);if(d)throw new M(d);if(!c.h.symlink)throw new M(63);c.h.symlink(c,b,a)},db=a=>{a=P(a).node;if(!a)throw new M(44);if(!a.h.readlink)throw new M(28);
return Ha(eb(a.parent),a.h.readlink(a))},qb=(a,b,c)=>{if(""===a)throw new M(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=K(a);try{e=P(a,{K:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new M(20);}else e=S(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==
(e.mode&61440))throw new M(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==ib(b)||b&512)?31:gb(e,ib(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?P(c,{K:!0}).node:c;if(!c.h.m)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=gb(c,"w"))throw new M(d);c.h.m(c,{size:0,timestamp:Date.now()})}b&=-131713;e=lb({node:e,path:eb(e),flags:b,seekable:!0,position:0,i:e.i,Z:[],error:!1});e.i.open&&e.i.open(e);!g.logReadFiles||
b&1||(pb||(pb={}),a in pb||(pb[a]=1));return e},rb=(a,b,c)=>{if(null===a.fd)throw new M(8);if(!a.seekable||!a.i.A)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.i.A(a,b,c);a.Z=[]},sb=()=>{M||(M=function(a,b){this.name="ErrnoError";this.node=b;this.Y=function(c){this.o=c};this.Y(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(a=>{Wa[a]=new M(a);Wa[a].stack="<generic error, no stack>"}))},tb,T=(a,b,c)=>{a=K("/dev/"+a);var d=Ya(!!b,!!c);ub||(ub=
64);var e=ub++<<8|0;Pa(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,k,n,u)=>{for(var l=0,p=0;p<u;p++){try{var t=b()}catch(A){throw new M(29);}if(void 0===t&&0===l)throw new M(6);if(null===t||void 0===t)break;l++;k[n+p]=t}l&&(f.node.timestamp=Date.now());return l},write:(f,k,n,u)=>{for(var l=0;l<u;l++)try{c(k[n+l])}catch(p){throw new M(29);}u&&(f.node.timestamp=Date.now());return l}});nb(a,d,e)},ub,U={},R,pb;
function vb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Q(a).path;if(0==b.length)throw new M(44);return K(a+"/"+b)}var Y=void 0;function Z(){Y+=4;return C[Y-4>>2]}
var wb={},yb=()=>{if(!xb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in wb)void 0===wb[b]?delete a[b]:a[b]=wb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xb=c}return xb},xb,zb=[];
function Ab(a,b,c,d){var e={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=La(l)+1;var t=Bb(p);Ma(l,B,t,p);p=t}return p},array:l=>{var p=Bb(l.length);z.set(l,p);return p}};a=g["_"+a];var f=[],k=0;if(d)for(var n=0;n<d.length;n++){var u=e[c[n]];u?(0===k&&(k=Cb()),f[n]=u(d[n])):f[n]=d[n]}c=a.apply(null,f);return c=function(l){0!==k&&Db(k);return"string"===b?l?L(B,l):"":"boolean"===b?!!l:l}(c)}
function hb(a,b,c,d){a||(a=this);this.parent=a;this.s=a.s;this.D=null;this.id=bb++;this.name=b;this.mode=c;this.h={};this.i={};this.rdev=d}Object.defineProperties(hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});sb();O=Array(4096);mb(N,"/");S("/tmp",16895,0);S("/home",16895,0);S("/home/web_user",16895,0);
(()=>{S("/dev",16895,0);Pa(259,{read:()=>0,write:(d,e,f,k)=>k});nb("/dev/null",259);Oa(1280,Ra);Oa(1536,Sa);nb("/dev/tty",1280);nb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ga(a).byteLength);return a[--b]};T("random",c);T("urandom",c);S("/dev/shm",16895,0);S("/dev/shm/tmp",16895,0)})();
(()=>{S("/proc",16895,0);var a=S("/proc/self",16895,0);S("/proc/self/fd",16895,0);mb({s:()=>{var b=Va(a,"fd",16895,73);b.h={lookup:(c,d)=>{var e=Q(+d);c={parent:null,s:{O:"fake"},h:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Gb={__syscall_fcntl64:function(a,b,c){Y=c;try{var d=Q(a);switch(b){case 0:var e=Z();return 0>e?-28:lb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Z(),d.flags|=e,0;case 5:return e=Z(),ma[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return C[Eb()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.o}},__syscall_getcwd:function(a,b){try{if(0===b)return-28;var c=La("/")+1;if(b<c)return-68;Ma("/",B,a,
b);return c}catch(d){if("undefined"==typeof U||"ErrnoError"!==d.name)throw d;return-d.o}},__syscall_ioctl:function(a,b,c){Y=c;try{var d=Q(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.u.T){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Z();C[e>>2]=25856;C[e+4>>2]=5;C[e+8>>2]=191;C[e+12>>2]=35387;for(var f=0;32>f;f++)z[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;
if(d.tty.u.U)for(e=Z(),b=[],f=0;32>f;f++)b.push(z[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=Z();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Z();if(!d.i.S)throw new M(59);return d.i.S(d,b,e);case 21523:if(!d.tty)return-59;d.tty.u.V&&(f=[24,80],e=Z(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(k){if("undefined"==typeof U||"ErrnoError"!==k.name)throw k;return-k.o}},__syscall_openat:function(a,
b,c,d){Y=d;try{b=b?L(B,b):"";b=vb(a,b);var e=d?Z():0;return qb(b,c,e).fd}catch(f){if("undefined"==typeof U||"ErrnoError"!==f.name)throw f;return-f.o}},__syscall_readlinkat:function(a,b,c,d){try{b=b?L(B,b):"";b=vb(a,b);if(0>=d)return-28;var e=db(b),f=Math.min(d,La(e)),k=z[c+f];Ma(e,B,c,d+1);z[c+f]=k;return f}catch(n){if("undefined"==typeof U||"ErrnoError"!==n.name)throw n;return-n.o}},_emscripten_get_now_is_monotonic:()=>!0,_emscripten_throw_longjmp:()=>{throw Infinity;},emscripten_date_now:function(){return Date.now()},
emscripten_get_now:()=>performance.now(),emscripten_memcpy_big:(a,b,c)=>B.copyWithin(a,b,b+c),emscripten_resize_heap:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ka.buffer.byteLength+65535>>>16;try{ka.grow(e);na();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},environ_get:(a,b)=>{var c=0;yb().forEach(function(d,e){var f=b+c;e=D[a+4*e>>
2]=f;for(f=0;f<d.length;++f)z[e++>>0]=d.charCodeAt(f);z[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:(a,b)=>{var c=yb();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});D[b>>2]=d;return 0},exit:a=>{if(!noExitRuntime){if(g.onExit)g.onExit(a);la=!0}ca(a,new ha(a))},fd_close:function(a){try{var b=Q(a);if(null===b.fd)throw new M(8);b.F&&(b.F=null);try{b.i.close&&b.i.close(b)}catch(c){throw c;}finally{ab[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==
c.name)throw c;return c.o}},fd_read:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,k=b=0;k<c;k++){var n=D[a>>2],u=D[a+4>>2];a+=8;var l=e,p=n,t=u,A=f,Ka=z;if(0>t||0>A)throw new M(28);if(null===l.fd)throw new M(8);if(1===(l.flags&2097155))throw new M(8);if(16384===(l.node.mode&61440))throw new M(31);if(!l.i.read)throw new M(28);var V="undefined"!=typeof A;if(!V)A=l.position;else if(!l.seekable)throw new M(70);var W=l.i.read(l,Ka,p,t,A);V||(l.position+=W);var F=W;if(0>F){var X=-1;break a}b+=F;if(F<
u)break;"undefined"!==typeof f&&(f+=F)}X=b}D[d>>2]=X;return 0}catch(J){if("undefined"==typeof U||"ErrnoError"!==J.name)throw J;return J.o}},fd_seek:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Q(a);rb(f,b,d);Aa=[f.position>>>0,(I=f.position,1<=+Math.abs(I)?0<I?+Math.floor(I/4294967296)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];C[e>>2]=Aa[0];C[e+4>>2]=Aa[1];f.F&&0===b&&0===d&&(f.F=null);return 0}catch(k){if("undefined"==typeof U||
"ErrnoError"!==k.name)throw k;return k.o}},fd_write:function(a,b,c,d){try{a:{var e=Q(a);a=b;for(var f,k=b=0;k<c;k++){var n=D[a>>2],u=D[a+4>>2];a+=8;var l=e,p=n,t=u,A=f,Ka=z;if(0>t||0>A)throw new M(28);if(null===l.fd)throw new M(8);if(0===(l.flags&2097155))throw new M(8);if(16384===(l.node.mode&61440))throw new M(31);if(!l.i.write)throw new M(28);l.seekable&&l.flags&1024&&rb(l,0,2);var V="undefined"!=typeof A;if(!V)A=l.position;else if(!l.seekable)throw new M(70);var W=l.i.write(l,Ka,p,t,A,void 0);
V||(l.position+=W);var F=W;if(0>F){var X=-1;break a}b+=F;"undefined"!==typeof f&&(f+=F)}X=b}D[d>>2]=X;return 0}catch(J){if("undefined"==typeof U||"ErrnoError"!==J.name)throw J;return J.o}},invoke_vii:Fb,system:a=>{if(m){if(!a)return 1;a=a?L(B,a):"";if(!a.length)return 0;a=require("child_process").ka(a,[],{ja:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return null===a.status?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;
case "SIGTERM":return 15}return 2})(a.signal)):a.status<<8|0}if(!a)return 0;C[Eb()>>2]=52;return-1}};
(function(){function a(c){y=c=c.exports;ka=y.memory;na();oa=y.__indirect_function_table;qa.unshift(y.__wasm_call_ctors);E--;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(0==E&&(null!==ta&&(clearInterval(ta),ta=null),G)){var d=G;G=null;d()}return c}var b={env:Gb,wasi_snapshot_preview1:Gb};E++;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return w("Module.instantiateWasm callback failed with error: "+c),!1}za(b,function(c){a(c.instance)});
return{}})();g._new_state=()=>(g._new_state=y.new_state)();g._free_state=()=>(g._free_state=y.free_state)();g._run_tea=a=>(g._run_tea=y.run_tea)(a);var Eb=()=>(Eb=y.__errno_location)(),Hb=(a,b)=>(Hb=y.setThrew)(a,b),Cb=()=>(Cb=y.stackSave)(),Db=a=>(Db=y.stackRestore)(a),Bb=a=>(Bb=y.stackAlloc)(a);g.dynCall_jiji=(a,b,c,d,e)=>(g.dynCall_jiji=y.dynCall_jiji)(a,b,c,d,e);
function Fb(a,b,c){var d=Cb();try{var e=zb[a];e||(a>=zb.length&&(zb.length=a+1),zb[a]=e=oa.get(a));e(b,c)}catch(f){Db(d);if(f!==f+0)throw f;Hb(1,0)}}g.ccall=Ab;g.cwrap=function(a,b,c,d){var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:function(){return Ab(a,b,c,arguments,d)}};var Ib;G=function Jb(){Ib||Kb();Ib||(G=Jb)};
function Kb(){function a(){if(!Ib&&(Ib=!0,g.calledRun=!0,!la)){g.noFSInit||tb||(tb=!0,sb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?T("stdin",g.stdin):ob("/dev/tty","/dev/stdin"),g.stdout?T("stdout",null,g.stdout):ob("/dev/tty","/dev/stdout"),g.stderr?T("stderr",null,g.stderr):ob("/dev/tty1","/dev/stderr"),qb("/dev/stdin",0),qb("/dev/stdout",1),qb("/dev/stderr",1));cb=!1;Ba(qa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=
[g.postRun]);g.postRun.length;){var b=g.postRun.shift();ra.unshift(b)}Ba(ra)}}if(!(0<E)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();Ba(pa);0<E||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Kb();
